#ifndef COMMON_WALFILTER_VERSIONS_RECORDPROCESSGPDB6_H
#define COMMON_WALFILTER_VERSIONS_RECORDPROCESSGPDB6_H

#include "common/walFilter/postgresCommon.h"

FN_EXTERN WalInterface getWalInterfaceGPDB6(PgPageSize heapPageSize);

#endif // COMMON_WALFILTER_VERSIONS_RECORDPROCESSGPDB6_H
